version: "3"
services:
  toy-redis:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080 # /metrics
      - 9999:9999 # tcp
    volumes:
      - ./tmp/var/log/:/var/log/
