version: "3"
services:
  grafana:
    image: grafana/grafana:10.2.1
    ports:
      - 3001:3000
    volumes:
      - grafana-data:/var/lib/grafana'
  prometheus:
    image: prom/prometheus:v2.48.0
    ports:
      - 9091:9090
    volumes:
      - prometheus-data:/prometheus
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  toy-redis:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080 # /metrics
      - 9999:9999 # tcp
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yml
    volumes:
      - ./monitoring/loki/loki.yml:/etc/loki/loki.yml

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - /var/log:/var/log
      - ./monitoring/promtail/promtail.yml:/etc/promtail/promtail.yml
    command: -config.file=/etc/promtail/promtail.yml

volumes:
  grafana-data:
  prometheus-data:
