# my global config
global:
  scrape_interval: 2s
  evaluation_interval: 30s

scrape_configs:
  - job_name: toyRedis
    metrics_path: /metrics
    honor_labels: false
    honor_timestamps: true
    scheme: http
    follow_redirects: true
    body_size_limit: 15MB
    sample_limit: 1500
    target_limit: 30
    label_limit: 30
    label_name_length_limit: 200
    label_value_length_limit: 200
    static_configs:
      - targets: ["toy-redis:8080", "prometheus:9090", "grafana:3000"]
